title: "Tran Thi Hong Nhi"
description: "Aspiring Data Analyst | Financial Analytics | Skilled in Python, SQL and Visualization"
theme: jekyll-theme-minimal

logo: /assets/profile.jpg
show_downloads: false

google_analytics: false
markdown: kramdown
